image: 'rust:latest'

stages:
  - test
  - build
  - push

before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass

test:
  stage: test
  tags: [gitlab-org]
  before_script:
    - rustc --version
    - cargo --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo test -- --nocapture

build_binary:
  stage: build
  only: [master]
  tags: [gitlab-org]
  before_script:
    - rustc --version
    - cargo --version
  script:
    - RUST_BACKTRACE=1 cargo build --release
  artifacts:
      paths:
        - target/release/${CI_PROJECT_NAME}

push_new:
  stage: push
  only: [master]
  tags: [gitlab-org]
  script:
    - cd target/release/${CI_PROJECT_NAME}
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no weeabot doctorworm@garappa.chat:/usr/bin/weeabotstuff
    - sshpass ssh doctorworm@garappa.chat sudo systemctl restart weeabot