image: 'rust:latest'

stages:
  - test
  - build

test:
  stage: test
  tags: [gitlab-org]
  before_script:
    - rustc --version
    - cargo --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo test -- --nocapture

build_binary:
  stage: build
  tags: [gitlab-org]
  only:
    - tags
  before_script:
    - rustc --version
    - cargo --version
  script:
    - RUST_BACKTRACE=1 cargo build --release
  artifacts:
      paths:
        - target/release/${CI_PROJECT_NAME}
