[package]
name = "weeabot"
version = "0.2.0"
authors = ["Ciaran Ainsworth <ciaranainsworth@posteo.net>"]
edition = "2018"

[dependencies]
matrix_bot_api = "0.4.0"
config = "0.9.3"
wana_kana = "0.9.3"
rand = "0.7.0"
ytr = "0.1.2"
tmdb = "2.0.0"