[package]
name = "weeabot"
version = "0.1.0"
authors = ["Ciaran Ainsworth <ciaranainsworth@posteo.net>"]
edition = "2018"

[dependencies]
matrix_bot_api = "0.4.0"
chrono = "0.4.6"
fractal-matrix-api = "4.0.0"
config = "0.9.2"
rand = "0.6.5"
