[package]
name = "weeabot"
version = "0.5.0"
authors = ["Ciarán Ainsworth <ciaranainsworth@posteo.net>"]
edition = "2018"

[dependencies]
matrix_bot_api = { git = "https://github.com/zwieberl/matrix_bot_api" }
config = "0.10.1"
wana_kana = "2.0.1"
rand = "0.7.3"
ytr = "0.1.2"
chrono = "0.4.11"